/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const start: () => void;
export const wgpu_render_bundle_draw: (a: number, b: number, c: number, d: number, e: number) => void;
export const wgpu_render_bundle_draw_indexed: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wgpu_render_bundle_set_pipeline: (a: number, b: bigint) => void;
export const wgpu_render_bundle_draw_indirect: (a: number, b: bigint, c: bigint) => void;
export const wgpu_render_bundle_set_bind_group: (a: number, b: number, c: bigint, d: number, e: number) => void;
export const wgpu_render_bundle_set_vertex_buffer: (a: number, b: number, c: bigint, d: bigint, e: bigint) => void;
export const wgpu_render_bundle_set_push_constants: (a: number, b: number, c: number, d: number, e: number) => void;
export const wgpu_render_bundle_draw_indexed_indirect: (a: number, b: bigint, c: bigint) => void;
export const wgpu_render_bundle_insert_debug_marker: (a: number, b: number) => void;
export const wgpu_render_bundle_pop_debug_group: (a: number) => void;
export const wgpu_render_bundle_set_index_buffer: (a: number, b: bigint, c: number, d: bigint, e: bigint) => void;
export const wgpu_render_bundle_push_debug_group: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_11336: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_1175: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_3354: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_2882: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_1174: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_2882_5: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_1174_6: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_3354_7: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_2882_8: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_2882_9: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_2882_10: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_2882_11: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_2881: (a: number, b: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_export5: (a: number, b: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_start: () => void;
