//! GENERATED by scripts/gen_legacy_aliases.py - read-side legacy-name
//! interop table (do not edit by hand; regenerate instead).
//!
//! WHAT THIS IS: user-supplied packs authored for the wider 1.16.5-era
//! ecosystem reference that ecosystem's own coined item/texture/mob
//! names in their paths and ids. This table maps those (as bare,
//! namespace-stripped keys) onto OUR vocabulary so real-world packs
//! keep loading - pure format interop, the same principle as reading
//! any foreign file format. We never WRITE any of the left-hand names.

/// (legacy ecosystem name, our name) - longest-first.
pub const LEGACY_NAME_ALIASES: &[(&str, &str)] = &[
    ("soul_sand_valley", "spirit_sand_valley"),
    ("totem_of_undying", "totem_of_revival"),
    ("end_portal_frame", "void_gate_frame"),
    ("wither_skeleton", "blight_skeleton"),
    ("crying_obsidian", "weeping_obsidian"),
    ("respawn_anchor", "rebirth_anchor"),
    ("depth_strider", "aqua_step"),
    ("soul_campfire", "spirit_campfire"),
    ("ender_dragon", "void_wyrm"),
    ("soul_lantern", "spirit_lantern"),
    ("eye_of_ender", "void_eye"),
    ("shroomlight", "glowcap"),
    ("end_crystal", "void_crystal"),
    ("ender_pearl", "void_pearl"),
    ("enderdragon", "voidwyrm"),
    ("end_arrival", "void_arrival"),
    ("wither_rose", "blight_rose"),
    ("ender_chest", "void_chest"),
    ("end_gateway", "void_gateway"),
    ("end_pillar", "void_pillar"),
    ("netherrack", "hollowstone"),
    ("prismarine", "abyssprism"),
    ("vindicator", "cleaver"),
    ("illusioner", "miragecaller"),
    ("the_nether", "the_hollow"),
    ("soul_speed", "spirit_speed"),
    ("end_portal", "void_gate"),
    ("soul_torch", "spirit_torch"),
    ("mooshroom", "shroomcow"),
    ("end_stone", "void_stone"),
    ("soul_soil", "spirit_soil"),
    ("soul_sand", "spirit_sand"),
    ("soul_fire", "spirit_fire"),
    ("endermite", "voidmite"),
    ("netherite", "hollowite"),
    ("redstone", "fluxstone"),
    ("soulsand", "spiritsand"),
    ("soul_dmg", "spirit_dmg"),
    ("creaking", "timberhaunt"),
    ("enderman", "voidling"),
    ("endermen", "voidlings"),
    ("shulker", "lurkshell"),
    ("crimson", "scarlet"),
    ("strider", "emberhopper"),
    ("creeper", "fuseling"),
    ("the_end", "the_void"),
    ("sniffer", "trufflehog"),
    ("end_rod", "void_rod"),
    ("warden", "depthbrute"),
    ("breeze", "zephyr"),
    ("zoglin", "rotboar"),
    ("wither", "blight"),
    ("nylium", "mold"),
    ("purpur", "violetstone"),
    ("warped", "viridian"),
    ("elytra", "skywings"),
    ("piglin", "pigoblin"),
    ("nether", "hollow"),
    ("hoglin", "boarling"),
    ("chorus", "echo"),
    ("evoker", "runecaller"),
    ("allay", "sootheling"),
    ("ghast", "weepgeist"),
    ("vex", "wisp"),
];

/// Resolve a bare name - or a name whose PREFIX is a legacy name
/// (`legacy_name_suffix`) - to our vocabulary. `None` = no match.
pub fn legacy_name_alias(bare: &str) -> Option<std::borrow::Cow<'static, str>> {
    for (old, new) in LEGACY_NAME_ALIASES {
        if bare == *old {
            return Some(std::borrow::Cow::Borrowed(*new));
        }
        if let Some(rest) = bare.strip_prefix(old) {
            if rest.starts_with('_') {
                return Some(std::borrow::Cow::Owned(format!("{new}{rest}")));
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exact_and_prefixed_names_resolve() {
        assert_eq!(legacy_name_alias("redstone"), Some("fluxstone".into()));
        assert_eq!(legacy_name_alias("creeper"), Some("fuseling".into()));
        assert_eq!(legacy_name_alias("enderman"), Some("voidling".into()));
        assert_eq!(legacy_name_alias("netherrack"), Some("hollowstone".into()));
        // prefix + suffix compounds (files/ids we never enumerated)
        assert_eq!(
            legacy_name_alias("crimson_pressure_plate"),
            Some("scarlet_pressure_plate".into())
        );
        assert_eq!(
            legacy_name_alias("soul_sand_valley"),
            Some("spirit_sand_valley".into())
        );
        // longest-first: wither_skeleton beats bare wither
        assert_eq!(
            legacy_name_alias("wither_skeleton"),
            Some("blight_skeleton".into())
        );
        // no match — our own names and unrelated names pass through
        assert_eq!(legacy_name_alias("stone"), None);
        assert_eq!(legacy_name_alias("oak_planks"), None);
    }
}
