//! GENERATED by scripts/gen_legacy_aliases.py - read-side legacy-name
//! interop table (do not edit by hand; regenerate instead).
//!
//! WHAT THIS IS: the 2026-09-20 round coined its own in-game vocabulary
//! (fluxstone/hollowstone/fuseling/...); the 2026-09-21 round restored
//! the REAL ecosystem terms as the project's own names. This table maps
//! the short-lived COINED names (as bare, namespace-stripped keys) onto
//! the real names, so packs or saves produced by the coined-era builds
//! keep loading — pure format interop. Real-name packs resolve natively
//! (identity) and never consult this table. We never WRITE the coined
//! names.

/// (legacy coined name, our name) - longest-first.
pub const LEGACY_NAME_ALIASES: &[(&str, &str)] = &[
    ("spirit_sand_valley", "soul_sand_valley"),
    ("totem_of_revival", "totem_of_undying"),
    ("weeping_obsidian", "crying_obsidian"),
    ("void_gate_frame", "end_portal_frame"),
    ("spirit_campfire", "soul_campfire"),
    ("blight_skeleton", "wither_skeleton"),
    ("rebirth_anchor", "respawn_anchor"),
    ("spirit_lantern", "soul_lantern"),
    ("viridian_mold", "warped_nylium"),
    ("void_crystal", "end_crystal"),
    ("miragecaller", "illusioner"),
    ("scarlet_mold", "crimson_nylium"),
    ("crimson_mold", "crimson_nylium"),
    ("spirit_speed", "soul_speed"),
    ("void_arrival", "end_arrival"),
    ("void_gateway", "end_gateway"),
    ("spirit_torch", "soul_torch"),
    ("spirit_fire", "soul_fire"),
    ("warped_mold", "warped_nylium"),
    ("void_pillar", "end_pillar"),
    ("emberhopper", "strider"),
    ("spirit_soil", "soul_soil"),
    ("spirit_sand", "soul_sand"),
    ("violetstone", "purpur"),
    ("timberhaunt", "creaking"),
    ("hollowstone", "netherrack"),
    ("blight_rose", "wither_rose"),
    ("trufflehog", "sniffer"),
    ("runecaller", "evoker"),
    ("depthbrute", "warden"),
    ("void_chest", "ender_chest"),
    ("abyssprism", "prismarine"),
    ("void_stone", "end_stone"),
    ("the_hollow", "the_nether"),
    ("void_pearl", "ender_pearl"),
    ("sootheling", "allay"),
    ("spiritsand", "soulsand"),
    ("spirit_dmg", "soul_dmg"),
    ("fluxstone", "redstone"),
    ("void_gate", "end_portal"),
    ("shroomcow", "mooshroom"),
    ("hollowite", "netherite"),
    ("aqua_step", "depth_strider"),
    ("void_wyrm", "ender_dragon"),
    ("voidlings", "endermen"),
    ("lurkshell", "shulker"),
    ("weepgeist", "ghast"),
    ("viridian", "warped"),
    ("void_eye", "eye_of_ender"),
    ("fuseling", "creeper"),
    ("voidwyrm", "enderdragon"),
    ("voidling", "enderman"),
    ("void_rod", "end_rod"),
    ("skywings", "elytra"),
    ("voidmite", "endermite"),
    ("boarling", "hoglin"),
    ("the_void", "the_end"),
    ("pigoblin", "piglin"),
    ("cleaver", "vindicator"),
    ("glowcap", "shroomlight"),
    ("scarlet", "crimson"),
    ("rotboar", "zoglin"),
    ("blight", "wither"),
    ("hollow", "nether"),
    ("zephyr", "breeze"),
    ("wisp", "vex"),
    ("echo", "chorus"),
    ("mold", "nylium"),
];

/// Resolve a bare name - or a name whose PREFIX is a legacy name
/// (`legacy_name_suffix`) - to our vocabulary. `None` = no match.
pub fn legacy_name_alias(bare: &str) -> Option<std::borrow::Cow<'static, str>> {
    for (old, new) in LEGACY_NAME_ALIASES {
        if bare == *old {
            return Some(std::borrow::Cow::Borrowed(*new));
        }
        if let Some(rest) = bare.strip_prefix(old) {
            if rest.starts_with('_') {
                return Some(std::borrow::Cow::Owned(format!("{new}{rest}")));
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exact_and_prefixed_names_resolve() {
        // coined-era names -> the restored real vocabulary
        assert_eq!(legacy_name_alias("fluxstone"), Some("redstone".into()));
        assert_eq!(legacy_name_alias("fuseling"), Some("creeper".into()));
        assert_eq!(legacy_name_alias("voidling"), Some("enderman".into()));
        assert_eq!(legacy_name_alias("hollowstone"), Some("netherrack".into()));
        // prefix + suffix compounds (files/ids we never enumerated)
        assert_eq!(
            legacy_name_alias("scarlet_pressure_plate"),
            Some("crimson_pressure_plate".into())
        );
        assert_eq!(
            legacy_name_alias("spirit_sand_valley"),
            Some("soul_sand_valley".into())
        );
        // longest-first: blight_skeleton beats bare blight
        assert_eq!(
            legacy_name_alias("blight_skeleton"),
            Some("wither_skeleton".into())
        );
        // the real names are now OUR names: they pass through the
        // loader natively and never consult this table (None = no
        // remapping needed — it is already our vocabulary)
        assert_eq!(legacy_name_alias("redstone"), None);
        // no match — unrelated names pass through
        assert_eq!(legacy_name_alias("stone"), None);
        assert_eq!(legacy_name_alias("oak_planks"), None);
    }
}
