#!/usr/bin/env python3
"""gen_legacy_aliases.py — regenerate crates/vc-pack/src/legacy_aliases.rs.

The canonical OLD->NEW vocabulary lives HERE (and only here);
scripts/rename_terms.py mirrors it. The table maps the wider 1.16.5-era
ecosystem's coined names (as bare, namespace-stripped keys) onto OUR
vocabulary — read-side format interop for user-supplied packs.
"""
import os

# (legacy ecosystem name, our name) — the canonical project vocabulary
PAIRS = [
    ("the_end", "the_void"), ("the_nether", "the_hollow"),
    ("enderdragon", "voidwyrm"), ("ender_dragon", "void_wyrm"),
    ("endermen", "voidlings"), ("enderman", "voidling"),
    ("endermite", "voidmite"),
    ("ender_chest", "void_chest"), ("ender_pearl", "void_pearl"),
    ("eye_of_ender", "void_eye"),
    ("end_portal_frame", "void_gate_frame"), ("end_portal", "void_gate"),
    ("end_gateway", "void_gateway"), ("end_crystal", "void_crystal"),
    ("end_stone", "void_stone"), ("end_rod", "void_rod"),
    ("end_pillar", "void_pillar"), ("end_arrival", "void_arrival"),
    ("netherrack", "hollowstone"), ("netherite", "hollowite"),
    ("nether", "hollow"),
    ("wither_skeleton", "blight_skeleton"), ("wither_rose", "blight_rose"),
    ("wither", "blight"),
    ("soul_sand_valley", "spirit_sand_valley"),
    ("soul_sand", "spirit_sand"), ("soul_soil", "spirit_soil"),
    ("soul_fire", "spirit_fire"), ("soul_torch", "spirit_torch"),
    ("soul_lantern", "spirit_lantern"), ("soul_campfire", "spirit_campfire"),
    ("soul_speed", "spirit_speed"), ("soul_dmg", "spirit_dmg"),
    ("soulsand", "spiritsand"),
    ("crimson", "scarlet"), ("warped", "viridian"), ("nylium", "mold"),
    ("redstone", "fluxstone"),
    ("creeper", "fuseling"), ("ghast", "weepgeist"),
    ("piglin", "pigoblin"), ("hoglin", "boarling"), ("zoglin", "rotboar"),
    ("depth_strider", "aqua_step"), ("strider", "emberhopper"),
    ("shulker", "lurkshell"), ("mooshroom", "shroomcow"),
    ("evoker", "runecaller"), ("vindicator", "cleaver"),
    ("illusioner", "miragecaller"),
    ("allay", "sootheling"), ("warden", "depthbrute"),
    ("breeze", "zephyr"), ("creaking", "timberhaunt"),
    ("sniffer", "trufflehog"),
    ("shroomlight", "glowcap"), ("purpur", "violetstone"),
    ("prismarine", "abyssprism"), ("chorus", "echo"),
    ("crying_obsidian", "weeping_obsidian"),
    ("respawn_anchor", "rebirth_anchor"),
    ("totem_of_undying", "totem_of_revival"),
    ("elytra", "skywings"),
    # bare-form display names that may appear in user-pack ids
    ("vex", "wisp"),
]

HEAD = '''//! GENERATED by scripts/gen_legacy_aliases.py - read-side legacy-name
//! interop table (do not edit by hand; regenerate instead).
//!
//! WHAT THIS IS: user-supplied packs authored for the wider 1.16.5-era
//! ecosystem reference that ecosystem's own coined item/texture/mob
//! names in their paths and ids. This table maps those (as bare,
//! namespace-stripped keys) onto OUR vocabulary so real-world packs
//! keep loading - pure format interop, the same principle as reading
//! any foreign file format. We never WRITE any of the left-hand names.

/// (legacy ecosystem name, our name) - longest-first.
pub const LEGACY_NAME_ALIASES: &[(&str, &str)] = &[
'''

FN = '''
/// Resolve a bare name - or a name whose PREFIX is a legacy name
/// (`legacy_name_suffix`) - to our vocabulary. `None` = no match.
pub fn legacy_name_alias(bare: &str) -> Option<std::borrow::Cow<'static, str>> {
    for (old, new) in LEGACY_NAME_ALIASES {
        if bare == *old {
            return Some(std::borrow::Cow::Borrowed(*new));
        }
        if let Some(rest) = bare.strip_prefix(old) {
            if rest.starts_with('_') {
                return Some(std::borrow::Cow::Owned(format!("{new}{rest}")));
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exact_and_prefixed_names_resolve() {
        assert_eq!(legacy_name_alias("redstone"), Some("fluxstone".into()));
        assert_eq!(legacy_name_alias("creeper"), Some("fuseling".into()));
        assert_eq!(legacy_name_alias("enderman"), Some("voidling".into()));
        assert_eq!(legacy_name_alias("netherrack"), Some("hollowstone".into()));
        // prefix + suffix compounds (files/ids we never enumerated)
        assert_eq!(
            legacy_name_alias("crimson_pressure_plate"),
            Some("scarlet_pressure_plate".into())
        );
        assert_eq!(
            legacy_name_alias("soul_sand_valley"),
            Some("spirit_sand_valley".into())
        );
        // longest-first: wither_skeleton beats bare wither
        assert_eq!(
            legacy_name_alias("wither_skeleton"),
            Some("blight_skeleton".into())
        );
        // no match — our own names and unrelated names pass through
        assert_eq!(legacy_name_alias("stone"), None);
        assert_eq!(legacy_name_alias("oak_planks"), None);
    }
}
'''


def main():
    pairs = sorted(set(PAIRS), key=lambda p: -len(p[0]))
    rows = "\n".join('    ("%s", "%s"),' % (a, b) for a, b in pairs)
    out = os.path.join(os.path.dirname(__file__), "..",
                       "crates/vc-pack/src/legacy_aliases.rs")
    with open(out, "w") as f:
        f.write(HEAD + rows + "\n];\n" + FN)
    print("regenerated %s: %d entries" % (out, len(pairs)))


if __name__ == "__main__":
    main()
