//! build.rs — embed the builtin resource pack into the binary (native only).
//!
//! The "single-file Linux game" goal (`.github/workflows/linux-game.yml`):
//! `voxelcraft` must run with ZERO companion files, so the 16-file
//! builtin pack (96K: blockstates / models / PNG textures / pack.mcmeta)
//! is copied into OUT_DIR at build time and exposed to the compiler as a
//! static `(&str, &[u8])` table via include_bytes!.
//!
//! Runtime precedence (game.rs): a real `builtin-pack/` folder next to the
//! working directory still WINS over the embedded copy — so dropping a
//! custom pack folder beside the binary overrides the baked-in one — and
//! when neither exists the engine falls back to procedural textures
//! (§46: an imperfect pack must never crash the engine).
//!
//! wasm32 is excluded: the browser build fetches the pack from
//! `/voxelcraft-pack/**` at boot (wasm-build.yml deploys it), and an
//! embedded copy would only double the .wasm payload.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // no-op on wasm (the module is cfg-gated too; keep the build honest)
    let target = env::var("TARGET").unwrap_or_default();
    if target.contains("wasm32") {
        return;
    }

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    // crates/voxelcraft -> workspace root -> builtin-pack
    let pack_root = manifest_dir
        .join("../..")
        .join("builtin-pack")
        .canonicalize()
        .expect("builtin-pack/ must exist at the workspace root");
    assert!(
        pack_root.join("pack.mcmeta").is_file(),
        "builtin-pack/pack.mcmeta missing (looked at {})",
        pack_root.display()
    );

    // rebuild when the pack changes
    println!("cargo:rerun-if-changed={}", pack_root.display());

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let staged = out_dir.join("embedded-pack");
    let _ = fs::remove_dir_all(&staged);
    fs::create_dir_all(&staged).expect("create OUT_DIR/embedded-pack");

    // walk the pack, copy every file to OUT_DIR, collect (relpath, size)
    let mut rows: Vec<(String, u64)> = Vec::new();
    let mut stack = vec![pack_root.clone()];
    while let Some(dir) = stack.pop() {
        for entry in fs::read_dir(&dir).expect("read pack dir") {
            let entry = entry.expect("pack dir entry");
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            let rel = path
                .strip_prefix(&pack_root)
                .expect("path under pack root")
                .to_string_lossy()
                .replace('\\', "/");
            let dest = staged.join(&rel);
            fs::create_dir_all(dest.parent().expect("parent dir")).expect("create nested dir");
            fs::copy(&path, &dest).expect("copy pack file");
            let len = entry.metadata().expect("pack file metadata").len();
            rows.push((rel, len));
        }
    }
    rows.sort();

    // generated statics: include_bytes! with OUT_DIR-relative literal paths
    // (concat! + env!("OUT_DIR") is resolved at macro-expansion time, so
    // the paths are compile-time constants — no runtime file access)
    let mut src = String::new();
    src.push_str("//! GENERATED by build.rs — the builtin pack, baked into the binary.\n");
    src.push_str("//! Each row: (pack-relative path, file bytes).\n");
    src.push_str("#![allow(clippy::all)]\n\n");
    src.push_str("pub static EMBEDDED_PACK_FILES: &[(&str, &[u8])] = &[\n");
    let mut total: u64 = 0;
    for (rel, len) in &rows {
        // sanitize the rel path into a stable identifier for the static
        total += len;
        src.push_str(&format!(
            "    (\"{rel}\", include_bytes!(concat!(env!(\"OUT_DIR\"), \"/embedded-pack/{rel}\"))),\n"
        ));
    }
    src.push_str("];\n");
    src.push_str(&format!(
        "pub static EMBEDDED_PACK_TOTAL_BYTES: u64 = {total};\n"
    ));
    fs::write(out_dir.join("embedded_pack.rs"), src).expect("write embedded_pack.rs");

    eprintln!(
        "[build.rs] embedded builtin-pack: {} files, {} bytes -> {}",
        rows.len(),
        total,
        out_dir.join("embedded_pack.rs").display()
    );
}
